### ISSUE TITLE
This is nice, chrome store?

### ISSUE THREAD

**Issue by 00MB** [natsuozawa/kited#3]
Publish this to the chrome store, also would be nice if you store the password securely so you could automatically bypass the login.

**Comment by natsuozawa** [comment]
Hi Michael, thanks for having a look around.

I currently do not have plans to publish in the chrome store because you have to pay a $5 fee, and I'm merely open sourcing a tool I made largely for myself. 
That being said, feel free to publish this on the store if you have an account. 

As for storing the password, the problem is that kited currently uses the web storage API which is not secure. This shouldn't be problematic though if you have your browser polyfill the password automatically. If the login button is being clicked before the password is polyfilled, please submit an issue

**Comment by 00MB** [comment]
I have an account, if I publish it on your behalf I will let you know!
